# Generated by Django 3.1.1 on 2020-09-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_timing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
